# This is a basic workflow to help you get started with Actions

name: CI

on:
  # Triggers the workflow on pull request for the master branch
  push:
    branches: [ master, stable ]
  pull_request:
    branches: [ master ]

jobs:
  # Run DepCtrl manifest verification
  verify-depctrl:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3.1.2
    
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python validate_depctrl.py
